### ISSUE TITLE
运行bsm-shell 出现问题。求帮助

### ISSUE THREAD

**Issue by FuchengZheng** [cqu-bdsc/DSRC-Tutorial#2]
root@MK5:/home/duser# ls -la
total 1778
drwxrwxr-x 1 duser duser    4096 Nov 13 00:01 .
drwxrwxr-x 1 root  root     4096 Nov 10 12:23 ..
-rw------- 1 duser duser   32768 Nov 12 09:16 .bash_history
-rw-r--r-- 1 duser duser     220 Apr  9  2014 .bash_logout
-rw-r--r-- 1 duser duser    3637 Apr  9  2014 .bashrc
drwx------ 1 duser duser    4096 Jan  1  1970 .cache
-rw-r--r-- 1 duser duser     675 Apr  9  2014 .profile
drwxrwxr-x 1 duser duser    4096 May 23  2018 .ssh
-rw-r--r-- 1 duser duser       0 Jan  1  1970 .sudo_as_admin_successful
-rwxrwxr-x 1 duser duser 1667278 Nov 13 00:09 bsm-shell
-rw-r--r-- 1 root  root    85707 Nov 12 23:57 bsmlog.txt
-rwxrwxr-x 1 duser duser     469 Nov 12 06:47 rc.local
root@MK5:/home/duser# D_LEVEL=4 ./bsm-shell -m 1 -c 178 -b 172 -n 172 -i 1 -f/dev/null -u 192.168.1.83 -y 4040 -z 4040
--LogFile=/dev/null
--ChanCCHA=178
--ChanSCHA=176
--ChanSCHB=172
--TxCounter=1
--ChanNbr=172
--ChannelMode=1
--DataRate=12
--TxPwr=64
--WsmPsid=0x00000010
--WbssPsid=0x000000ff
--UdpAddr=192.168.1.83
--UdpTxPort=0x0fc8
--UdpRxPort=0x0fc8
[0x40280]:Lib1609_GnlMsgWrite ERROR: Lib1609_GnlMsgWrite: generic netlink ack failed: -1003
[0x40280]:Lib1609_GnlMsgWrite ERROR: Lib1609_GnlMsgWrite: generic netlink ack failed: -1003
ShellVICAction: Brakes Released
^CSignal 2!
main ERROR: Poll error 4 'Interrupted system call'

**Comment by neardws** [comment]
这个问题我没遇到过，不过这边可以提供我们运行的正常结果提供参考。
![WechatIMG1](https://user-images.githubusercontent.com/23012163/68739168-2efa5080-0623-11ea-9760-99df6c93f79b.png)
![WechatIMG2](https://user-images.githubusercontent.com/23012163/68739179-36215e80-0623-11ea-9f93-e35680df13bf.png)
另外，可以给你提供些建议。

1. 检查bsm-shell进程是否在运行
2. 如果在运行，可以尝试通过2台设备进行通信看看是否能够发送和接收到信息
3. 如果还是不行，可以向Cohda Wireless的[技术支持](https://support.cohdawireless.com/)寻求帮助

**Comment by FuchengZheng** [comment]
谢谢指导。
已检查好bsm-shell进程是在运行。
请问如何通过2台设备进行通信？ 如何发送和接收信息？
求教学

**Comment by siyu-0120** [comment]
感谢教程指导
请问能够运行bsm-shell以后，如何实现PC机发送和接收信息？
求教学
